controller_list:
  - name: arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: gripper_controller
    joints:
      - joint6
      - joint7A
      - joint7B
