arm_controller:
   type: "position_controllers/JointTrajectoryController"
   action_ns: follow_joint_trajectory
   default: true
   joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

gripper_controller:
   type: "position_controllers/JointTrajectoryController"
   action_ns: follow_joint_trajectory
   default: true
   joints:
      - joint7A
      - joint7B


